apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  telegram-token: {{ .Values.telegramToken | b64enc }}
  jwt-secret: {{ include "utils.secret.keepOrCreate" (dict "namespace" .Release.Namespace "name" ${{ .Release.Name }}-secrets "key" "jwt-secret") }}
