---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt
data:
  jwt-secret: {{ include "utils.secret.keepOrCreate" (dict "namespace" .Release.Namespace "name" (printf "%s-secrets" .Release.Name) "key" "jwt-secret") }}
---
{{- if and .Values.telegramToken.value (not .Values.telegramToken.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-telegram-token
stringData:
  telegram-token: {{ .Values.telegramToken.value }}
{{- end }}
---
{{- if and .Values.datasource.uri (not .Values.datasource.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-datasource
stringData:
  datasource-uri: {{ .Values.datasource.uri }}
{{- end }}
