spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: mood-tracker
    password: ${DATASOURCE_PASSWORD}

mood-tracker:
  configuration:
    host: "https://moody-dev.twaslowski.com/configure"
