spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mood_tracker?currentSchema=mood-tracker
    username: mood-tracker
    password: password

mood-tracker:
  metrics:
    config-path: src/main/resources/metrics.yml
  configuration:
    url: "http://localhost:3000/configure"
    jwt:
      key: a-string-secret-at-least-256-bits-long
      expiry: 86400