server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: false

spring:
  application:
    name: mood-tracker
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "\"mood-tracker\""
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1260000
  flyway:
    schemas: mood-tracker

mood-tracker:
  metrics:
    config-path: /app/config/defaults.yml
  telegram:
    bot:
      token: ${TELEGRAM_TOKEN}
    scheduled:
      auto-baseline:
        cron: 0 0 22 * * *
      notification:
        recording-reminder:
          cron: 0 0 18 * * *
          text: "It's time to record your mood! Just press /record"

management:
  endpoints:
    web:
      exposure:
        include: health
