spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mood-tracker?currentSchema=mood-tracker
    username: user
    password: password

mood-tracker:
  metrics:
    config-path: src/main/resources/metrics.yml
  configuration:
    host: "http://localhost:3000/configure"
    jwt:
      key: a-string-secret-at-least-256-bits-long