ALTER TABLE "user" ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE "record" ALTER COLUMN user_id TYPE VARCHAR(255);
ALTER TABLE "configuration" ALTER COLUMN user_id TYPE VARCHAR(255);
ALTER TABLE "notification" ALTER COLUMN user_id TYPE VARCHAR(255);
ALTER TABLE "metric" ALTER COLUMN owner_id TYPE VARCHAR(255);

DROP SEQUENCE IF EXISTS user_id_seq;

DROP TABLE IF EXISTS configuration_session;

CREATE SEQUENCE IF NOT EXISTS record_id_seq START 1 INCREMENT 50;