environment: dev
datasource:
  url: "jdbc:postgresql://postgres.mood-tracker-dev.svc.cluster.local:5432/mood-tracker?currentSchema=mood_tracker"

ingress:
  enabled: true
  className: "cloudflare-tunnel"
  hosts:
    - host: "moody-dev.twaslowski.com"
      paths:
        - path: /api/
          pathType: Prefix

metrics:
  tracked:
    - Mood
    - Sleep

  defaults:
    - name: Mood
      description: "How are you feeling right now?"
      minValue: -3
      maxValue: 2
      defaultValue: 0
      sortOrder: DESC
      labels:
        - value: 2
          label: Manic
        - value: 1
          label: Hypomanic
        - value: 0
          label: Neutral
        - value: -1
          label: Mildly Depressed
        - value: -2
          label: Depressed
        - value: -3
          label: Severely Depressed

    - name: Sleep
      description: "How many hours did you sleep last night?"
      minValue: 4
      maxValue: 12
      defaultValue: 8

    - name: Energy
      description: "How much energy do you have right now?"
      minValue: 0
      maxValue: 5
      defaultValue: 3

    - name: Appetite
      description: "How much appetite are you experiencing?"
      minValue: 0
      maxValue: 4
      defaultValue: 2
      labels:
        - value: 0
          label: None
        - value: 1
          label: Low
        - value: 2
          label: Normal
        - value: 3
          label: High
        - value: 4
          label: Ravenous

    - name: Stress
      description: "How stressed are you right now?"
      minValue: 0
      maxValue: 5
      defaultValue: 1

#notifications:
#  - description: "Recording reminder"
#    message: "It's time to record your mood! Just press /record"
#    schedule: "0 0 18 * * *"
