architecture: standalone

auth:
  username: mood-tracker
  database: mood-tracker
nameOverride: "postgres"

service:
  port: 5432

primary:
  resourcesPreset: nano

persistence:
  primary:
    size: 2Gi
